[package]
name = "aws_ssh"
version = "0.1.0"
authors = ["Vlad Vasiliu <code@vladvasiliu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
external-ip = "1.0"
fern = "0.6"
log = "0.4"
roxmltree = "0.11"
rusoto_core = "0.43.0"
rusoto_credential = "0.43.0"
rusoto_ec2 = "0.43.0"
tokio = { version = "0.2", features = ["rt-core", "macros"] }

[dev-dependencies]
