[package]
name = "aws_ssh"
version = "0.1.0"
authors = ["Vlad Vasiliu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33", features = ["color"] }
external-ip = "1.0"
fern = "0.6"
log = "0.4"
roxmltree = "0.11"
rusoto_core = "0.43.0"
rusoto_ec2 = "0.43.0"
tokio = { version = "0.2", features = ["rt-core", "macros"] }
blob-uuid = "0.4"

[dev-dependencies]
rusoto_mock = "0.43"