[package]
name = "aws_ssh"
version = "0.1.0"
authors = ["Vlad Vasiliu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~2.33", features = ["color"] }
#confy = "0.4"
external-ip = "~2.0"
fern = "~0.6"
http = "~0.2.1"
lazy_static = "~1.4"
log = "~0.4"
regex = "~1"
roxmltree = "~0.11"
rusoto_core = "~0.45"
rusoto_ec2 = "~0.45"
tokio = { version = "~0.2", features = ["rt-core", "macros"] }

[dev-dependencies]
rusoto_mock = "~0.45"
