[package]
name = "aws_doorman"
version = "0.1.1"
authors = ["Vlad Vasiliu"]
edition = "2018"

[dependencies]
clap = { version = "~2.33", features = ["color"] }
#confy = "0.4"
color-eyre = "0.5"
external-ip = "~4.0"
fern = "~0.6"
http = "~0.2"
lazy_static = "~1.4"
log = "~0.4"
regex = "~1"
#roxmltree = "~0.11"
rusoto_core = "~0.45"
rusoto_ec2 = "~0.45"
tokio = { version = "~0.2", features = ["rt-core", "macros", "signal", "time"] }

[dev-dependencies]
rusoto_mock = "~0.45"

[profile.release]
lto = true
incremental = true
codegen-units = 1
panic = "abort"

[profile.dev.package.backtrace]
opt-level = 3